ENV: 'local'

START_DATE: '20190101'
PREDICTION_PERIOD: 3600

MONGO_DB: 'mongodb://localhost:27017/mercadolibre'

PLANET_1_DISTANCE: 500
PLANET_1_SPEED: 1

PLANET_2_DISTANCE: 2000
PLANET_2_SPEED: 3

PLANET_3_DISTANCE: 1000
PLANET_3_SPEED: -5
